#!/bin/sh

if [ $# -ne 1 ]; then 
	echo "$0 prefix"
	exit 1 
fi

# From now on, abort on first error
set -e

locate -0 -r "^$1.*/refs/heads$" | sed -r 's,/(logs/)?refs/heads,,g' | sort -z -u | xargs -0 git-gc
